### ISSUE TITLE
documentation is missing and status of SDK 

### ISSUE THREAD

**Issue by vineetpant** [status-im/Keycard.swift#23]
I recently tested keycard SDK Integration on Android and it is working fine.  But IOS SDK for keycard doesn't seem to be regularly updated and documentation seems missing as well  . Is it ready to start development and integrate Keycard SDK on IOS? or Do you know by when it will be ready?

**Comment by bitgamma** [comment]
Please refer to documentation of the Android SDK. The two SDK expose the same API with the exception of the way the connection to the card is established.

You can see an example at https://github.com/gnosis/KeycardExample

The SDK is ready to be used and will continue to be maintained. Since yesterday it can also be used through Cocoapods.

**Comment by vineetpant** [comment]
Hi , I am working on a react native application and i want the react native app to use keycard in the same way for Android and IOS . is it possible ?

**Comment by bitgamma** [comment]
Yes, please have a look at https://github.com/status-im/react-native-status-keycard/tree/feature/ios to see how we are doing it (it's work in progress but mostly done)
